### ISSUE TITLE
ReadMe example does not work

### ISSUE THREAD

**Issue by nick-konovalchuk** [mkhorasani/Streamlit-Authenticator#102]
I've literally copied and pasted code from ReadMe
```python
import streamlit as st
import streamlit_authenticator as stauth

import yaml
from yaml.loader import SafeLoader

with open('config.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)

authenticator.login('Login', 'main')

if st.session_state["authentication_status"]:
    authenticator.logout('Logout', 'main', key='unique_key')
    st.write(f'Welcome *{st.session_state["name"]}*')
    st.title('Some content')
elif st.session_state["authentication_status"] is False:
    st.error('Username/password is incorrect')
elif st.session_state["authentication_status"] is None:
    st.warning('Please enter your username and password')
```

Used `hashed_passwords = stauth.Hasher(['abc', 'def']).generate()` to get the hashed passwords, so my config file ended up being following:
```yaml
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$agCxCe4dqZwqrNchoCDIW.oIjkmf4yBOpDDvTQfBLvFh4Kl6Xh7Oi
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$BoZxbxrWJmHRgCsSYtG7tOQlh2c113YzoGeo4Q6Sb6sh8xTzP.wMm
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
```
I'm failing to login with John Smith, abc.
`stauth.Hasher` generates different hashes every time. Is it expected?
