### ISSUE TITLE
Empty credentials for registration only apps

### ISSUE THREAD

**Issue by lambda-science** [mkhorasani/Streamlit-Authenticator#125]
Hello, thank you very much for this fantastic package. It helps a lot put streamlit apps into "semi-production".
I want to ask, is it possible do to an initial empty `config.yaml` like:
```yaml
cookie:
  expiry_days: 1
  key: some_signature_key
  name: streamlit-pythia-auth
preauthorized:
  emails: 
    - aa@bb.cc
    - aa2@bb.cc
    - aa3@bb.cc
```
So a `yaml` that doesn't contain initial `credentials` key but only preauthorized email so that we can push it to our private repo without pushing initial "admin account" hash ?
Basically I want to push my auth yaml file to my repo for deploymenent with a restricted list of user that will use it, but I don't want to put an initial account inside it.
