### ISSUE TITLE
Getting random_cookie_name error

### ISSUE THREAD

**Issue by hunaidkhan2000** [mkhorasani/Streamlit-Authenticator#134]
Hi @mkhorasani  thanks for this amazing package, I kindly request your assistance with an issue that's surfaced with a Streamlit app we've recently deployed on Azure cloud. From yesterday, we've been encountering a peculiar 'Random_cookie_name' error that's preventing some users from logging out. It's interesting to note that it's not a universal issue - some of our users from different geographical locations are able to logout without trouble. To assist you in troubleshooting, I'm attaching a screenshot along with a sample yml file and script. Your expertise and guidance on this matter would be greatly appreciated.
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/34857371/6dff119b-2056-4d21-aa2c-c6e982de2984) 
yml file 
````
credentials:
  usernames:
    hk:
      email: hk@gmail.com
      name: hkhan
      password: "my hashed password" # 
##some other user names 
#file ends with 
cookie:
  expiry_days: 0
  key: "random_signature_key" # Must be a string
  name: "random_cookie_name" #we did not change it , kept it as random_cookie_name 
preauthorized:
  emails:
  - hk@gmail.com
```


our main file authentication code is 
```
with open('chatbot_users.yml') as file:  ##../
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)
```
