### ISSUE TITLE
no cookie is written - help would be great ;) 

### ISSUE THREAD

**Issue by Volker-H** [mkhorasani/Streamlit-Authenticator#176]
I've tried a lot but I can't get it to work - any help would be much appreciated
Problem is that no cookie is written. So the reauthentication is not working.

here are the versions used:
```
Package                    Version
-------------------------- ---------
extra-streamlit-components 0.1.71
streamlit                  1.36.0
streamlit-authenticator    0.3.2
```

part of the yaml:

```
cookie:
  expiry_days: 30
  key: secretkey
  name: dashboard
credentials:
  usernames:
    test:
      email: test.test@test.de
      failed_login_attempts: 0
      group: default
      logged_in: false
      name: test
      password: $2b$12$KbRDEDBX12ju9IbKB1Pg4eeX9bN8oTnuM1Oj.8TGXvGa/UAvdPPzG
pre-authorized:
  emails:
  - test@t.com

```

and my main app.py which handles the login and redirects to the next page if login ist succsessful

```
"""
in app.py ist die initiale Authentifizierung (Login). 
"""

import os
import sys
import streamlit as st
import streamlit_authenticator as stauth
import yaml
from yaml.loader import SafeLoader
from dotenv import load_dotenv
from loguru import logger
from helper.paths import (
    get_userdata_file_path,
    get_favicon,
    get_root_dir,
    get_logfile_path,
)
from helper.site_elements import footer, hide_st
from menu import menu

userfile = get_userdata_file_path()
root_dir = get_root_dir()
favicon = get_favicon()
st.set_page_config(layout="wide", page_icon=favicon, page_title="net.D Dashboard")


def load_user_config():
    """Laden der Userkonfig"""
    with open(userfile, encoding="utf-8") as file:
        user_data = yaml.load(file, Loader=SafeLoader)
        logger.debug("Userconfig geladen")
    return user_data


def update_userconf():
    """Funktion zum speichern der Userdaten"""
    with open(userfile, "w", encoding="utf-8") as file:
        yaml.dump(config, file, default_flow_style=False)
        logger.debug("userfile updated")


load_dotenv()


@st.cache_resource
def configure_logging():
    """konfiguriert den Logger - in funktion wegen Streamlit"""
    loglevel = os.environ.get("LOGLEVEL")
    logger.remove()
    logger.add(
        get_logfile_path(),
        rotation="3 days",
        retention=3,
        colorize=True,
        level=loglevel,
    )
    logger.add(sys.stderr)


configure_logging()


config = load_user_config()
authenticator = stauth.Authenticate(
    config["credentials"],
    config["cookie"]["name"],
    config["cookie"]["key"],
    config["cookie"]["expiry_days"],
    config["pre-authorized"]
)


if "group" not in st.session_state:
    st.session_state.group = None

st.title("Login Page")
st.divider()
authenticator.login(clear_on_submit=True)
if st.session_state["authentication_status"]:
    st.session_state.group = config["credentials"]["usernames"][
        st.session_state.username
    ]["group"]
    st.switch_page("pages/dashboard.py")
    # st.write("hier ist der switch zum dashboard")

elif st.session_state["authentication_status"] is False:
    st.session_state.group = None
    st.error("Username / Passwort falsch.")
elif st.session_state["authentication_status"] is None:
    st.session_state.group = None
    st.warning("Bitte Username und Passwort eingeben.")

update_userconf()


menu()  # Render the dynamic menu!

footer()
hide_st()


```
