### ISSUE TITLE
Authentication with [experimental] guest_login can't keep user after refresh

### ISSUE THREAD

**Issue by informatica92** [mkhorasani/Streamlit-Authenticator#226]
I'm trying to create a very simple application based only on Google authentication.
At the moment the code is the following: 

`main.py`
```python
import streamlit as st
import streamlit_authenticator as stauth

import yaml
from yaml.loader import SafeLoader

with open('config.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days']
)

# st.write(st.session_state)
# st.write(config)

if st.session_state['authentication_status']:
    st.write(f'Welcome *{st.session_state["name"]}*')
elif st.session_state['authentication_status'] is None:
    user = authenticator.experimental_guest_login('Login with Google', provider='google', oauth2=config['oauth2'])
```

`config.yaml`
```
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: 429....googleusercontent.com
    client_secret: GO...94
    redirect_uri: http://localhost:8501
```

![image](https://github.com/user-attachments/assets/53c79a19-b828-407c-8c75-7b43bbec57b4)

When I run this script the first time (starting wit no cookies) everything works as expected and after the google account selection, the page appears like this: 
![image](https://github.com/user-attachments/assets/7fc17d3e-f4e9-4870-b5be-7aa2786afc23)

But now, if I try to refresh the page, what I get is: 
![image](https://github.com/user-attachments/assets/94849fb9-ad27-4fcf-870f-090e4a144757)

The app is running locally at the moment (localhost:8501).

Have you ever experienced such a behavior? 
Is there a way to fix?
(I know it is experimental)

**Comment by mkhorasani** [comment]
Hi @informatica92, this is because you are not re-saving the config file as shown in [step 13](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#13-updating-the-config-file) of the readme file. This is required so that when you refresh the webpage and the re-authentication cookie is read, it can find the details of the guest user in the config file.

**Comment by informatica92** [comment]
Thank @mkhorasani for the fast reply.
I tried as you said but the issue is still there.

The code is now: 
```python
import streamlit as st
import streamlit_authenticator as stauth

import yaml
from yaml.loader import SafeLoader

with open('config.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days']
)

st.write(st.session_state)
# st.write(config)

st.write(st.session_state['authentication_status'])

if st.session_state['authentication_status'] is not None:
    print("authentication_status is NOT None")
    st.write(f'Welcome *{st.session_state["name"]}*')
    with open('config.yaml', 'w') as file:  # NEW SECTION AS YOU ASKED
        yaml.dump(config, file, default_flow_style=False)
else:
    print("authentication_status None")
    authenticator.experimental_guest_login('Login with Google', provider='google', oauth2=config['oauth2'])
```

The issue persists also because the config file hasn't changed that much. It's now 
```yaml
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames: {}
oauth2:
  google:
    client_id: 42...nt.com
    client_secret: GO...94
    redirect_uri: http://localhost:8501
preauthorized: null
```

It looks that the only updated parts are: `usernames: {}` and `preauthorized: null` in which the explicit empty value (empty dict and None/null) have been added
