### ISSUE TITLE
oauth2 "guest" login just redirects back to app without going to microsoft

### ISSUE THREAD

**Issue by Rob-murphys** [mkhorasani/Streamlit-Authenticator#229]
I am trying to use the newly relrease Oauth2 functionality but when I pretty the "Log in with microsoft" button I just get redirected to the app.
My `config.yml looks` like this:
```
cookie:
  expiry_days: 5
  key: 0d4ea227cca5c37e5050aac3ca8f0cd4
  name: some_name
oauth2:
  microsoft:
    client_id: some-id
    client_secret: some-secret
    redirect_uri: http://localhost:8501
    tenant_id: some-id
```

In the code for the app I have this:
```
authenticator = stauth.Authenticate(
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    auto_hash=True,
)
# Microsoft login widget
try:
    authenticator.experimental_guest_login('Login with Microsoft',
                                           provider='microsoft',
                                           oauth2=config['oauth2'])
except LoginError as e:
    st.error(e)
```

But as said above, when I pretty the button I am just redirected back to the app. I presume I am doing something wrong but I just dont know what!
