### ISSUE TITLE
All users being allowed to register after "pre-authorized" list becomes empty

### ISSUE THREAD

**Issue by pallav445** [mkhorasani/Streamlit-Authenticator#233]
Assume that the "pre-authorized" parameter in config.yaml contains 10 email IDs. Now, if all 10 users (defined in the list) finish with their registration, their email IDs get deleted from "pre-authorized" and the **register_user** method starts allowing all users to register thereby defeating the purpose of this parameter

**Comment by pallav445** [comment]
Hi @mkhorasani, I have encountered this issue. Here's what happened:

1. `config.yaml`: Initial state
```
credentials:
  usernames:
pre-authorized: 
- u1@testmail.com
```
2. After registering u1@testmail.com
```
credentials:
  usernames:
    u1@testmail.com:
      email: u1@testmail.com
      first_name: User
      last_name: One
      logged_in: false
      password: $2b$12$sK6am.2wEC/wsRcKxtglQOJvgGKA7OT6lVaPZ96yfDCHrzo7JwN3W
      password_hint: x
      roles: null
pre-authorized: []
```
3. After attempting to register u2@testmail.com
```
credentials:
  usernames:
    u1@testmail.com:
      email: u1@testmail.com
      first_name: User
      last_name: One
      logged_in: false
      password: $2b$12$sK6am.2wEC/wsRcKxtglQOJvgGKA7OT6lVaPZ96yfDCHrzo7JwN3W
      password_hint: x
      roles: null
    u2@testmail.com:
      email: u2@testmail.com
      first_name: User
      last_name: One
      logged_in: false
      password: $2b$12$hni7pdFJ1LFnTAmeLbXVH.KqygfVZgxULFnZNiLrlFvs2TM.GKNiu
      password_hint: x
      roles: null
pre-authorized: []
```
