### ISSUE TITLE
Unusable login window flicker when using `streamlit==1.43.0`

### ISSUE THREAD

**Issue by this-josh** [mkhorasani/Streamlit-Authenticator#265]
I have this minimal app

```python
# app.py
import streamlit as st
import yaml
from yaml.loader import SafeLoader
import streamlit_authenticator as stauth

with open("config.yaml") as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config["credentials"],
    config["cookie"]["name"],
    config["cookie"]["key"],
    config["cookie"]["expiry_days"],
)
authenticator.login()

if st.session_state["authentication_status"]:
    st.title("Foo bar")
elif st.session_state["authentication_status"] is False:
    st.error("Username/password is incorrect")
elif st.session_state["authentication_status"] is None:
    st.warning("Please enter your username and password")
```

and yaml
```yaml
credentials:
  usernames:
    a:
      password: b
      name: A
      email: a@b.com

cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name

pre-authorized:
  emails:
  - a@b.com
```

## working okay

Uv pyproject
```toml
[project]
name = "st"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "streamlit==1.42.0",
    "streamlit-authenticator==0.4.1",
    "watchdog==6.0.0",
]
```
## Not working 

```toml
dependencies = [
    "streamlit==1.43.0",
    "streamlit-authenticator==0.4.2",
    "watchdog>=6.0.0",
]
```
`streamlit-authenticator` version `0.4.1` also does not work

The minimal working example app can be seen [here](https://github.com/this-josh/st_auth_issue)

This issue is exhibited on both Chrome and Safari on my Mac; I'm not sure if it is a streamlit issue or for this repo 

## The bug

This video shows what happens
https://github.com/user-attachments/assets/e40aafde-2ea6-469d-8c0c-41e58439437b
