### ISSUE TITLE
Constant authentication_status == False

### ISSUE THREAD

**Issue by aishworyann** [mkhorasani/Streamlit-Authenticator#61]
hi , i was just working with streamlit-authenticator and was making a login page usng config.yaml , but it always outputing the authentication_status as False , however i have done exactly the same as there was in docs. Please help me to resolve this.
Also while deploying it on streamlit cloud, it was not getting the credentials from the repo .

**Comment by mkhorasani** [comment]
Hi @aishworyann, if possible can you please share your source code and perhaps also your config file?

**Comment by aishworyann** [comment]
Yeah sure @mkhorasani , and thanks for replying sir.Below i am attaching screenshots of the code.
<img width="1175" alt="Screenshot 2023-04-25 at 12 05 12 AM" src="https://user-images.githubusercontent.com/75421318/234085799-6245b52b-093a-422f-a754-e575c4ab3d22.png">
<img width="1175" alt="Screenshot 2023-04-25 at 12 05 20 AM" src="https://user-images.githubusercontent.com/75421318/234085822-c214d683-289a-492d-b920-f1fad3528c7c.png">
<img width="912" alt="Screenshot 2023-04-25 at 12 05 01 AM" src="https://user-images.githubusercontent.com/75421318/234085826-00fa338c-b9f7-4e83-83ef-a850e9a8474e.png">
Sir , i have tried using your given  default example code too but same thing is happening.

**Comment by aishworyann** [comment]
Below i have updated the config.yaml file using the hash generated and which i have used after updating the hash value(ignore the upper config file)
<img width="1284" alt="Screenshot 2023-04-25 at 12 08 00 AM" src="https://user-images.githubusercontent.com/75421318/234086243-e1859607-2dcf-446c-8faa-dca83a173749.png">

**Comment by mkhorasani** [comment]
If possible please share the source code as a text file, it'll be a lot easier for me to debug it that way. Thanks.

**Comment by mnsosa** [comment]
I have the same issue.

**Comment by mkhorasani** [comment]
Can you please share your source code if possible.

**Comment by C4rlit0** [comment]
Same issue here too, my source code is simple as your readme : 

app.py
```import yaml
from yaml.loader import SafeLoader
import streamlit as st
import streamlit_authenticator as stauth
from config import debug_mode
from airtable_utils import fetch_data_from_airtable

import folium
import streamlit_folium as stf

from pages import docs

# Set the title of the app
st.title("Demo Streamlit Auth")

with open('./config.yml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)

name, authentication_status, username = authenticator.login('Login', 'sidebar')

if authentication_status:
    authenticator.logout('Logout', 'main', key='unique_key')
    st.write(f'Welcome *{name}*')
    st.title('Some content')
elif authentication_status is False:
    st.error('Username/password is incorrect')
elif authentication_status is None:
    st.write('You\'re not logged in')
    docs.show()
```

config.yml
```
cookie:
  expiry_days: 30
  key: joiquclqsijflqsknjvqeluihfjomIJNQOIEJCRFGLHGFKEQOIMZXfJFO
  name: streamlit-auth-cookie
credentials:
  usernames:
    charly:
      email: sample1@mail.com
      name: Buddy Sample
      password: $2b$12$5IZZ5MM9jNi/CCaQE9Eq4ufKMbKmCxqZbvm2aQOvu1nau871TuqSO
    romain:
      email: sample2@mail.com
      name: John Doe
      password: $2b$12$znk0zJpJmkhnajKZHjyCiujVGrDDiCeQypwXva/zsGY2H9M8dI/DO
preauthorized:
  emails:
  - sample1@mail.com
```
